plugins {
  id 'application'
  id 'checkstyle'
  id 'com.adarshr.test-logger' version '4.0.0'
  id 'com.github.ben-manes.versions' version '0.54.0'
  id 'io.ebean' version '17.6.0'
  id 'jacoco'
}

group = 'io.hexlet'
version = '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}

compileJava {
  options.release = 19
  options.encoding = 'UTF-8'
}

application {
  mainClass = 'io.hexlet.blog.App'
}

dependencies {
  implementation 'io.javalin:javalin:7.2.2'
  implementation 'io.javalin:javalin-rendering:7.2.2'
  implementation 'org.slf4j:slf4j-simple:2.0.18'

  implementation 'org.thymeleaf:thymeleaf:3.1.5.RELEASE'
  implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:4.0.1'
  implementation 'org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE'
  implementation 'org.webjars:bootstrap:5.3.8'

  implementation 'com.h2database:h2:2.4.240'
  implementation 'org.postgresql:postgresql:42.7.11'

  implementation 'io.ebean:ebean:17.6.0'
  implementation 'io.ebean:ebean-ddl-generator:17.6.0'
  implementation 'io.ebean:ebean-querybean:17.6.0'
  implementation 'io.ebean:ebean-migration:14.3.0'
  implementation 'io.ebean:ebean-annotation:8.4'
  annotationProcessor 'io.ebean:querybean-generator:17.6.0'

  // NOTE: ebean-ddl-generator требует старые зависимости, которых нет в java 9 и выше
  implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.8'
  implementation 'javax.activation:activation:1.1.1'

  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.0.3'
  testImplementation 'org.junit.jupiter:junit-jupiter-params:6.0.3'
  testImplementation 'org.assertj:assertj-core:3.27.7'
  testImplementation 'io.ebean:ebean-test:17.6.0'
  testImplementation 'com.konghq:unirest-java:3.14.5'
}

test {
  useJUnitPlatform()
}

testlogger {
  showStandardStreams true
}

jacocoTestReport {
  reports {
    xml.required = true
  }
}

checkstyle {
  toolVersion '10.12.1'
}

task generateMigrations(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'io.hexlet.blog.MigrationGenerator'
}

task stage(dependsOn: ['clean', 'installDist'])
installDist.mustRunAfter clean
