plugins {
  id 'application'
  id 'com.adarshr.test-logger' version '4.0.0'
  id 'com.diffplug.spotless' version '8.8.0'
  id 'com.github.ben-manes.versions' version '0.54.0'
  id 'io.ebean' version '19.3.0'
  id 'jacoco'
}

group = 'io.hexlet'
version = '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}

compileJava {
  options.release = 19
  options.encoding = 'UTF-8'
}

application {
  mainClass = 'io.hexlet.blog.App'
}

dependencies {
  implementation 'io.javalin:javalin:7.2.2'
  implementation 'io.javalin:javalin-rendering-thymeleaf:7.2.2'
  implementation 'org.slf4j:slf4j-simple:2.0.18'

  implementation 'org.thymeleaf:thymeleaf:3.1.5.RELEASE'
  implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.4.0'
  implementation 'org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE'
  implementation 'org.webjars:bootstrap:5.3.8'

  implementation 'com.h2database:h2:2.4.240'
  implementation 'org.postgresql:postgresql:42.7.13'

  implementation 'io.ebean:ebean:19.3.0'
  implementation 'io.ebean:ebean-ddl-generator:19.3.0'
  implementation 'io.ebean:ebean-querybean:19.3.0'
  implementation 'io.ebean:ebean-migration:14.3.0'
  implementation 'io.ebean:ebean-annotation:8.11'
  annotationProcessor 'io.ebean:querybean-generator:19.3.0'

  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.14.4'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
  testImplementation 'org.junit.jupiter:junit-jupiter-params:5.14.4'
  testImplementation 'org.assertj:assertj-core:3.27.7'
  testImplementation 'io.ebean:ebean-test:19.3.0'
  testImplementation 'com.konghq:unirest-java:3.14.5'
}

test {
  useJUnitPlatform()
}

testlogger {
  showStandardStreams = true
}

jacocoTestReport {
  reports {
    xml.required = true
  }
}

spotless {
  java {
    target 'src/**/*.java'
    importOrder()
    removeUnusedImports()
    trimTrailingWhitespace()
    endWithNewline()
    leadingTabsToSpaces(4)
  }
}

task generateMigrations(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'io.hexlet.blog.MigrationGenerator'
}

task stage(dependsOn: ['clean', 'installDist'])
installDist.mustRunAfter clean
