DROP TABLE IF EXISTS articles;

CREATE TABLE articles (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                          VARCHAR(255),
  description                   TEXT,
  created_at                    TIMESTAMP NOT NULL,
  updated_at                    TIMESTAMP NOT NULL,
  CONSTRAINT pk_article PRIMARY KEY (id)
);
