-- apply changes
create table article (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  description                   text,
  created_at                    timestamptz not null,
  updated_at                    timestamptz not null,
  constraint pk_article primary key (id)
);

